name: 'ng2_playground'
version: 0.0.1
description: >
  An absolute bare-bones web app.
author: Andres Araujo <a.araujo.azua@gmail.com>
#homepage: https://www.example.com
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  angular2: "2.0.0-alpha.46"
  json_object: "^1.0.19"
dev_dependencies:
  dart_to_js_script_rewriter: '^0.1.0+4'
  browser: '^0.10.0+2'
transformers:
  - angular2:
      entry_points: web/main.dart
  - dart_to_js_script_rewriter
