name: 'ng2_playground'
version: 0.0.1
description: >
  An absolute bare-bones web app.
author: Andres Araujo <a.araujo.azua@gmail.com>
#homepage: https://www.example.com
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  angular2: ">=2.0.0-alpha.28 <3.0.0"
  jsonp_request: "^0.0.1"
  browser: any
