name: 'ng2_playground'
version: 0.0.1
description: >
  An absolute bare-bones web app.
author: Andres Araujo <a.araujo.azua@gmail.com>
#homepage: https://www.example.com
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  angular2: "2.0.0-alpha.32"
#  angular2:
#     git: git://github.com/andresaraujo/ng2_dart_snapshot.git
  json_object: "^1.0.19"
  browser: any
transformers:
  - angular2:
      entry_points: web/main.dart
